# Copyright 2017 Emil Dotchevski
# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

dist: trusty

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

addons:
  apt:
    packages:
      - g++-4.7
      - g++-4.8
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.6
      - clang-3.7
      - clang-3.8
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++0x

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.7 CXXSTD=c++0x

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.8 CXXSTD=c++0x

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.9 CXXSTD=c++0x

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++0x

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++0x

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=c++0x

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.7 CXXSTD=c++0x

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=c++0x

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++0x

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/inspect
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/exception
  - python tools/boostdep/depinst/depinst.py exception
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - ./b2 libs/exception/test toolset=$TOOLSET

notifications:
  email:
    on_success: always
